### ISSUE TITLE
Unable to make http requests

### ISSUE THREAD

**Issue by Luiz-N** [motdotla/node-lambda#100]
I have a lambda function that uses the firebase sdk to make updates to a firebase backend. This works fine when deployed but when ran locally via `node-lambda run` there are no errors and everything seems to work but nothing happens in firebase. It seems all outbound calls are muted? Perhaps I'm missing something?

**Comment by DeviaVir** [comment]
Please add a test-case so we can easily reproduce and see if we can fix this problem. It however sounds like a local problem, separate from `node-lambda`.
