### ISSUE TITLE
Right way to handle multiple environments?

### ISSUE THREAD

**Issue by Meekohi** [motdotla/node-lambda#101]
I'm a little lost on the philosophy behind how to use this tool to manage different environments (i.e. connecting to a local _development_ database, but then having the deployed version connect to the _production_ database). What I was expecting was to have `development.env`,`staging.env` and `production.env` files, but that doesn't seem like the strategy taken. Any tips to point me in the right direction? Does `deploy.env` get ignored in development and then can overwrite variables in production?

**Comment by DeviaVir** [comment]
This is one way of doing it:
https://github.com/motdotla/node-lambda/pull/95
