### ISSUE TITLE
Should not exit() after callback in node 4.3

### ISSUE THREAD

**Issue by GitTom** [motdotla/node-lambda#110]
The announcement of the node 4.3.2 runtime for lambda highlights the new, improved handling of the callback that user code does to end the lambda and return a result:  
https://aws.amazon.com/blogs/compute/node-js-4-3-2-runtime-now-available-on-lambda/

The take-away is that the process does not get killed by default.  (It looks like a good improvement to me.)

So, I think that this exit (and the one a few lines up): 
https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L64
are incorrect handling for 4.3.  It should be something like

```
if (!context.callbackWaitsForEmptyEventLoop) 
  process.exit(0);
else
  // end but don't kill process
```

But I'm a total js/node newbie so let me know if I'm missing something obvious.  Also, I'm not the right person to actual make the change if I'm right.

**Comment by DeviaVir** [comment]
@GitTom Thanks for chiming in! I'm afraid I'm not exactly following what the problem is you're trying to point out here. We're killing the process since we've returned the callback and there's nothing else to do.

**Comment by GitTom** [comment]
Here is some sample code that simulates a long async call:

```
   setTimeout(function() {
        console.log('hello timeout.');
   }, 4000); 
   callback( null, res );     // pass result back to lambda
```

If I run this on lambda 4.3 then it waits, keeps the process alive, and then prints "hello timeout".

If I run it with node-lambda, it kills the process in callback, so "hello timeout" doesn't get printed.  I believe that the code I linked to above should be changed so it doesn't kill the process.

**Comment by DeviaVir** [comment]
@GitTom that, to me, looks like a wrong way to handle callbacks, the reason we have callbacks, is so we can call a function when we're done executing code. It would fit better if the callback was called in the `setTimeout` function. This could however be my opinionated look at NodeJS.

**Comment by GitTom** [comment]
Ok, I see it is closed now, and like I say, I'm a node & js newbie, so I'll leave it be.  Thanks for quick responses.

**Comment by thundo** [comment]
@DeviaVir I totally understand your point. However you get different flows running handlers with Lambda and with your runner. You can get the same only if you set in Lambda  `context.callbackWaitsForEmptyEventLoop = false` ([default is true](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html#nodejs-prog-model-context-properties))

I think you should reconsider this behaviour.
