### ISSUE TITLE
Package and Deploy on Windows

### ISSUE THREAD

**Issue by pmosconi** [motdotla/node-lambda#114]
Hi, I am exploring node-lambda and I find it really useful for development and debug: thanks!

I am working on Windows, and I discovered that package and deploy don't work:

    Error: Command failed: mkdir -p C:\Users\PAOLOM~1\AppData\Local\Temp/S3FileProcess-1466246171476
    Command syntax error.

It would be very nice to have these features in Windows too.
paolo

**Comment by DeviaVir** [comment]
@pmosconi we're not officially supporting Windows at the moment, but this problem looks like it could be solved by using Bash on Windows.

Take a look at https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/

**Comment by pmosconi** [comment]
I was using the git bash on windows that is better than the plain old dos
cmd but still doesn't work.
I am familiar with the news you pointed out and hopefully this new feature
will solve a lot of problems when it will be rolled out.

paolo mosconi

**Comment by murphybob** [comment]
It could be a handy convenience to note on your readme very briefly that windows is not supported.  As this is a nodejs tool I'd assumed it was and it took me a bit of confusion (I ended up reading the source where it became obvious) before I realised node-lambda wasn't going to work out for me.

**Comment by teebu** [comment]
@pmosconi if you want, you can try my fork (its a bit old, i've been using it for a long time on windows) that i've made to work on windows https://github.com/teebu/node-lambda

**Comment by AnthonyWC** [comment]
I have it working on babun (windows); I think you just need to get npm/node working properly and it involves dos2unix IIRC.

**Comment by danielclariondoor** [comment]
This is crazy. You don't support windows?

**Comment by DeviaVir** [comment]
We're using [node-zip](https://www.npmjs.com/package/node-zip) as our [zip](https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L208)ping tool

I'd advise directing any issues or questions that arise out of this upstream.

**Comment by coldacid** [comment]
@DeviaVir the problem isn't with node-zip, it's with fs-extra.

**Comment by talawahdotnet** [comment]
Can you guys update the README to indicate that Windows isn't supported please? It would save people some time and trouble

**Comment by DeviaVir** [comment]
@talawahdotnet I will gladly approve and merge a PR with your suggested changes, thanks!

**Comment by seoker** [comment]
resolved by 2ee586f9c056f7052e77f773ab5ecb1a07d01faf
