### ISSUE TITLE
Skip aws-sdk node_module automatically

### ISSUE THREAD

**Issue by RafalWilinski** [motdotla/node-lambda#119]
This module is of course required for local testing (if you're doing any interactions with AWS) however, it's not needed to upload it with package to AWS. It's already bundled with every Lambda function according to this page: http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by teebu** [comment]
Dont include aws-sdk in your package.json and it won't install it.

**Comment by mkamla** [comment]
Would recommend adding AWS SDK module to dev dependencies as @teebu mentioned:

`npm install aws-sdk --save-dev`

Will work in your local/dev environment, but will not result in a duplicate module in Lambda production.

**Comment by RafalWilinski** [comment]
Thanks @mkamla
