### ISSUE TITLE
Add support for manually triggering the deployed lambda

### ISSUE THREAD

**Issue by pimterry** [motdotla/node-lambda#120]
`node-lambda run` is useful locally, but it would be helpful to be able to trigger the deployed lambda from the command line.

Would you be interested in a PR to add an API for this? I'm imagining something like `node-lambda trigger`.

**Comment by DeviaVir** [comment]
I can see how that can be useful for people, but don't have a specific use-case for it now.

**Comment by jakelodwick** [comment]
You can invoke Lambda functions with the AWS CLI's "lambda invoke" method

Docs: http://docs.aws.amazon.com/cli/latest/reference/lambda/invoke.html

**Comment by pimterry** [comment]
I still think this is useful, but I don't actually need it myself anymore, so I'm unlikely to get around to a PR any time soon, sorry. Anybody else interested should feel free to pick it up themselves!

**Comment by DeviaVir** [comment]
https://github.com/motdotla/node-lambda#post-invoke-script-example
