### ISSUE TITLE
Add support for schedule lambdas to run repeatedly

### ISSUE THREAD

**Issue by pimterry** [motdotla/node-lambda#121]
It would be useful for my use case (and I think many others) to be able to set a lambda running on a schedule (with CloudWatch events).

Would you be interested in a PR to add an API for this? I'm imagining something like `node-lambda schedule --rate "5 minutes"`.

**Comment by DeviaVir** [comment]
Sounds interesting for sure, curious how that would work with CloudWatch events. +1

**Comment by netaisllc** [comment]
We do this all the time (no pun intended). Off the top of my head, you'll need more AWS API calls than to just Lambda to handle use cases wherein the Cloudwatch event definition did not already exist. The function and the event def are isolated objects, right?

**Comment by DeviaVir** [comment]
https://github.com/motdotla/node-lambda#scheduleevents
