### ISSUE TITLE
Trying to deploy but get: RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation

### ISSUE THREAD

**Issue by cmhsu-cs** [motdotla/node-lambda#123]
Hi,

I'm running this command: node-lambda deploy --functionName mediaTestLambda --handler app.handler --environment production --accessKey process.env.AWS_KEY --secretKey process.env.AWS_SECRET --region us-east-1 --configFile deploy.env --packageDirectory './application-name.zip'

but it keeps giving me this error: RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation

I already ran $ node-lambda package --packageDirectory './' successfuly, and it created an application-name.zip file in my root directory. 

The app is rather small, so I don't think the size is the problem. Any help would be appreciated. Thanks!

**Comment by DeviaVir** [comment]
I'm not seeing a specific limit on the `CreateFunction` (AWS: http://docs.aws.amazon.com/lambda/latest/dg/API_FunctionCode.html#SSS-Type-FunctionCode-ZipFile), so I'm not too sure how to respond to this. Does it work if you try it with a simple test app?

**Comment by DeviaVir** [comment]
An alternative path for larger projects, is to use the `package` command, and upload your package using S3.
