### ISSUE TITLE
Using excludeGlobs with asterisk or multiple args breaks package cmd

### ISSUE THREAD

**Issue by helmutkian** [motdotla/node-lambda#125]
I cannot provide multiple arguments or globs prefixed with an asterisk ``*`` to the excludeGlobs option for the package command. For example running the command ``node-lambda package -p ./ -f deploy.env -x *.json`` causes the exception. ``packageDirectory not specified!`` to be thrown. The same with ``node-lambda package -p ./ -f deploy.env -x event.json package.json``

Using node-lambda 0.8.6.

**Comment by DeviaVir** [comment]
@helmutkian in the `README` it's exampled like this: `-x "event.json package.json"`, please give that a try
