### ISSUE TITLE
node 4 callback param not working

### ISSUE THREAD

**Issue by ksnyde** [motdotla/node-lambda#131]
I'm using nodejs4.3 and have declared the handler as:

```js
exports.handler = function handler(event, context, cb)
```

But when I call the `cb` callback I get the error:

> TypeError: cb is not a function

**Comment by DeviaVir** [comment]
@ksnyde did you also set `AWS_RUNTIME` to `nodejs4.3`?

**Comment by ksnyde** [comment]
I didn't but it stated that this was default. Somewhere in the past hour though I reflexively ran a `npm install -g node-lambda` and it does now work so I must have just been on an older version. Closing issue as it's not reproducible.
