### ISSUE TITLE
Environment variables when running locally

### ISSUE THREAD

**Issue by ksnyde** [motdotla/node-lambda#132]
When I run locally with:

```sh
node-lambda run
```

I am not getting the environment variables from the `deploy.env` file. Also, unlike the deployment commands there is no `-f` switch to choose a separate file (aka, for me this gives me ability to test locally the ENV of various environments).

**Comment by sesteva** [comment]
+1 on local env variables

**Comment by ersel** [comment]
It would be great to have the -f switch on local as well. The workaround I use is to mock env variables within the event.json file, and inside your lambda function you could do something like:

`var environmentVar = process.env.databaseString || event.databaseString`

So whilst running locally it will get the data from event object, if deployed to AWS it will use the environment variables.

**Comment by DeviaVir** [comment]
Thanks again @ersel for your PR fixing this issue, when the release is done it will be added via version [0.8.7](https://github.com/motdotla/node-lambda/issues/128)
