### ISSUE TITLE
Add support for lambci/docker-lambda

### ISSUE THREAD

**Issue by jghaines** [motdotla/node-lambda#168]
`node-lambda build` gives the following (sensible) warning on macOS:
`Warning!!! You are building on a platform that is not 64-bit Linux (darwin.x64). If any of your Node dependencies include C-extensions, they may not work as expected in the Lambda environment.`

One way to build on non-Linux platforms is [lambci/docker-lambda](https://github.com/lambci/docker-lambda) project that creates a Lambda-like environment in docker.

A `node-lambda build --docker` option would be great.

**Comment by DeviaVir** [comment]
https://github.com/motdotla/node-lambda/pull/251
