### ISSUE TITLE
CircleCI Deploy Random Fails

### ISSUE THREAD

**Issue by Fluidbyte** [motdotla/node-lambda#169]
We seem to be able to run deploys on our project fine locally, and about 50% of the time when it goes to [CircleCI](https://circleci.com), but then we get this the other 50% (a re-run of the build has been our working solution):

```
/home/ubuntu/webhooklambda/node_modules/node-lambda/lib/main.js:470
      throw err;
      ^

Error: Command failed: /bin/sh -c npm -s install --production --prefix /tmp/webhooklambda-1478469112072

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

This [appears to be on the archive process](https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L470) but I can't establish any reason why it's occuring, especially given its hit-or-miss nature.

If it helps replicate, here's our deploy script:

```bash

#!/bin/bash

DEP_ENV="production"

if [ $CIRCLE_BRANCH != "master" ]
  then DEP_ENV=$CIRCLE_BRANCH
fi

LAMBDA_NAME=$(grep -m1 name package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')

echo "NODE_ENV=$DEP_ENV" > deploy.env

node-lambda deploy \
  -e $DEP_ENV \
  -a $AWS_ACCESS_KEY_ID \
  -s $AWS_SECRET_ACCESS_KEY \
  -m $AWS_LAMBDA_MEMORY \
  -o $AWS_LAMBDA_ROLE_ARN \
  -n $LAMBDA_NAME \
  -u nodejs4.3 \
  -f deploy.env
```

Which just gets called via an `npm` script from the `circle.yml`.

**Comment by stephen-ta** [comment]
Does the `/bin/sh -c npm -s install --production --prefix /tmp/webhooklambda-1478469112072` command need to be run as root/sudo?

**Comment by Fluidbyte** [comment]
It turned out to be an issue with installing locally instead of globally. Once we installed `node-lambda` globally as part of the deploy process it started working fine.
