### ISSUE TITLE
Feature idea: Lambda environment variables

### ISSUE THREAD

**Issue by DominikPalo** [motdotla/node-lambda#170]
AWS recently added support of environment variables for Lambda functions (http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html).

It would be nice to implement this useful feature also to node-lambda.

**Comment by netaisllc** [comment]
Also, your **readme.md** says this

> AWS Lambda doesn't let you set environment variables for your function,

which is now, as you know, out of date.  Didn't do a PR as I'm not sure what your all plans for this are. :)

**Comment by DeviaVir** [comment]
@netaisllc I'd imagine a PR that adds support for the lambda env variables plus an update to the readme is in order. Once I have a few spare moments this is definitely one of the things I want to add support for, if someone beats me to it.. all the better!

**Comment by DeviaVir** [comment]
props to https://github.com/motdotla/node-lambda/pull/181

**Comment by RickDT** [comment]
If I already have some Environment Variables defined on the backend (in the Lambda console), deploying with `node-lambda deploy` appears to clear them out (it looks like it just overwrites them with an empty list of env vars). Is there a way to skip that or not update the env vars?

**Comment by abetomo** [comment]
@RickDT
Environment variables can also be set by explicitly specifying with the `-f` option.
`-f, --configFile [] Path to file holding secret environment variables (e.g. "deploy.env")`

PR #221, the environment variable is not updated when `-f` is not specified.

**Comment by RickDT** [comment]
Thanks. #221 and 0.9 works great!
