### ISSUE TITLE
Inserting env vars clobbers 'use strict';

### ISSUE THREAD

**Issue by CKarper** [motdotla/node-lambda#171]
If you have `'use strict';` at the top of your files, the inserted 
```javascript
////////////////////////////////////
// "Environment Variables"
process.env["environment"]="staging";
////////////////////////////////////
```
goes above it, rendering it non-working.

It'd be nice if the insertion would honor a `use strict` clause.

**Comment by DeviaVir** [comment]
This has been murdered by https://github.com/motdotla/node-lambda/pull/181/files#diff-16b7d75b70953cbf4755508170f2f24cL279 so it should be resolved if you grab the latest version `0.8.12`, if not feel free to reopen this ticket.
