### ISSUE TITLE
Could you guys add the environmental variable that to the .readme?

### ISSUE THREAD

**Issue by rxmg-nickk** [motdotla/node-lambda#176]
These are the ones I've figured out.  I don't know how to set the vpc net/sub or iam roles.

AWS_FUNCTION_NAME=
AWS_ENVIRONMENT=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=
AWS_HANDLER=
AWS_MEMORY_SIZE=
AWS_TIMEOUT=
AWS_DESCRIPTION=
AWS_RUNTIME=
EXCLUDE_GLOBS=
PACKAGE_DIRECTORY=
AWS_ROLE_ARN=

**Comment by DeviaVir** [comment]
For how to use them, please see:
https://github.com/motdotla/node-lambda/blob/master/README.md#deploy

For a list of all environment variables, please see:
https://github.com/motdotla/node-lambda/blob/master/bin/node-lambda#L13

**Comment by rxmg-nickk** [comment]
Thank you!

**Comment by DeviaVir** [comment]
https://github.com/motdotla/node-lambda#deploy-env-variables
