### ISSUE TITLE
Add new context methods/properties

### ISSUE THREAD

**Issue by nmaves** [motdotla/node-lambda#178]
It would be nice to have context.getRemainingTimeInMillis() implementing when running locally.

There are other that would be nice as well and can be found [here](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html).

To help implement the getRemainingTimeInMillis() I would think we could add a timeout command line option.

**Comment by DeviaVir** [comment]
https://github.com/motdotla/node-lambda/pull/179
https://github.com/motdotla/node-lambda/pull/180
fixed by you? :+1:
