### ISSUE TITLE
ResourceConflictException: Function already exist

### ISSUE THREAD

**Issue by jugaltheshah** [motdotla/node-lambda#182]
I get this error when I try to deploy a function that I've previously deployed. Of course I can delete the function from Lambda manually and deploy, but that kind of feels like it's defeating the purpose (creating an easier deployment process). Am I missing something?

Possibly relates to and would be solved by issue #49, but not sure.

**Comment by DeviaVir** [comment]
hi @jugaltheshah, there is a fair bit of logic for checking if a function already exists and this has for sure worked in the past:
https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L517
I have not tried it recently but it might be a change on AWS API's that is messing this up.

**Comment by aohrvall** [comment]
Check the permissions of the user that you use to upload the function. Something like this did the trick for me, even if it might be a bit permissible.

        {
            "Sid": "CreateFunctionPermissions",
            "Effect": "Allow",
            "Action": [
                "lambda:*"
            ],
            "Resource": "*"
        },

**Comment by DeviaVir** [comment]
Is this still an active problem?

**Comment by jugaltheshah** [comment]
Sorry I have not had occasion to use Lambda recently. Will check and report back, hopefully within the next 12 hours.

**Comment by tyshcr** [comment]
I was getting the same error. When I added @aohrvall 's suggested IAM Policy, I was able to overwrite existing Lambdas.

Here is the Policy I created:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "CreateFunctionPermissions",
            "Effect": "Allow",
            "Action": [
                "lambda:*"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by tyshcr** [comment]
I also got a `ResourceConflictException` when I had an invalid value in `.env` for the `AWS_VPC_SUBNETS`, despite the fact that my terminal output was saying ` message: Function already exists`

I tried changing my `AWS_FUNCTION_NAME` in `.env` and got the terminal to say `The subnet ID \'subnet-75b240a\' does not exist'` ... at which point I re-checked my subnets and found an error.

**Comment by devops-at-alinea** [comment]
My `ResourceConflictException` disappeared when I explicitly included the deploy.env (note: I also had some vars set in it)
```
node-lambda deploy -f ~/workspace/deploy.env
```

For future reference, here are the IAM permissions I have set in order to deploy:
```
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "lambda:UpdateFunctionCode",
                "iam:PassRole",
                "lambda:UpdateFunctionConfiguration"
            ],
            "Resource": "*"
        }
```

**Comment by AmirSasson** [comment]
i am getting the same error, when specifying subnet  and security group.
double checked , all seems to be configured right.
lambda deployment updates work when not specifying subnets.
any clue? i am lost here...

**Comment by teebu** [comment]
I'm getting `ResourceConflictException: Function already exist: ` error as well. I can't figure out what the problem is. The node-lambda should handle the existence, and works locally on my machine, but is throwing this error when deploying in travis. 

I installed directly from this git repo. I set the IAM for the `lambda:*` just to make sure. It creates a new function, but wont update existing one.
