### ISSUE TITLE
deploy.env

### ISSUE THREAD

**Issue by mooreniemi** [motdotla/node-lambda#192]
I'm trying to use `--configFile deploy.env` to inject some RDS env vars. When I do so though, my lambda then reports the following on test:

> Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

I exported the code, unzipped, and found that the env var block is added above where I put `"use strict";`. If I move that above the env var block, and redeploy manually by uploading a packaged zip, the error disappears. I don't see how this would make sense though.

What do you make of this?

**Comment by DeviaVir** [comment]
@mooreniemi what version of node-lambda are you using?

**Comment by mooreniemi** [comment]
`node-lambda@0.8.11`

**Comment by DeviaVir** [comment]
@mooreniemi would you mind trying the same with `0.8.13`?

**Comment by mooreniemi** [comment]
Sure: just reran with 0.8.13, same result.

**Comment by DeviaVir** [comment]
That's not possible, the reason I ask you to try `0.8.13` is that [this piece of code](https://github.com/motdotla/node-lambda/blob/0.8.11/lib/main.js#L279) which does the substitution has been fully removed and replaced by [lambda environment variables](https://github.com/motdotla/node-lambda/blob/0.8.13/lib/main.js#L147). Please double check if you updated to `0.8.13` correctly.

**Comment by mooreniemi** [comment]
Yeah sorry, looks like I was using a globally installed executable that was older, didn't realize.
