### ISSUE TITLE
Lambda Secret Variable

### ISSUE THREAD

**Issue by petervkay** [motdotla/node-lambda#193]
Where can I find the credentials in order to run "deploy" successfully?

- thanks!

**Comment by DeviaVir** [comment]
Hi @petervkay, this project assumes you have a working AWS CLI and have ran "aws configure" (so you have an `~/.aws/` folder with `credentials`. Soon as that is set up, this project (and many other AWS projects!) should magically start working for you

**Comment by DeviaVir** [comment]
(closing because sort-of off-topic to node-lambda)
