### ISSUE TITLE
Unable to update an existing node.js 0.10.36 runtime to 4.3

### ISSUE THREAD

**Issue by ncfcmark** [motdotla/node-lambda#195]
I am unable to update an existing lambda function's runtime from 0.10.36 to 4.3 when also upgrading node-lambda to the latest version from 0.7.1. It appears that there have been some changes in how the `UpdateFunctionConfiguration` API is called - the `runtime` parameter is no longer included. I assume that's deliberate, but it appears to cause problems when attempting to make an update to an older Lambda function, as the change to runtime is never triggered.

**Comment by vladaman** [comment]
+1 same issue

**Comment by DeviaVir** [comment]
This  has been restored
