### ISSUE TITLE
Support nodejs6.10 (now available for Lambda)

### ISSUE THREAD

**Issue by bluepeter** [motdotla/node-lambda#201]
Setting `AWS_RUNTIME=nodejs6.10` gives me a `runtime is not defined` error.

**Comment by abetomo** [comment]
There is PR in open! https://github.com/motdotla/node-lambda/pull/197

**Comment by bluepeter** [comment]
@motdotla can we get movement on this please...

**Comment by DeviaVir** [comment]
@bluepeter thank you for your patience, this change is now live for version `0.8.14`
