### ISSUE TITLE
Suggest to remove 'rsync' dependency

### ISSUE THREAD

**Issue by seoker** [motdotla/node-lambda#211]
As I noticed that this library depends on `rsync` to copy the whole folder to a temporary folder, however the command/tool might not be supported in some other OS (like Windows).

I think it's better to remove the dependency on such command/tool.

**Comment by DeviaVir** [comment]
Duplicates https://github.com/motdotla/node-lambda/issues/124

As stated in #114 I am in no means against adding Windows support and will merge any PR that adds this functionality. Looking forward to see a PR resolving this.

**Comment by seoker** [comment]
resolved by 2ee586f9c056f7052e77f773ab5ecb1a07d01faf
