### ISSUE TITLE
Is there a missing callback parameter in the handler method in index.js?

### ISSUE THREAD

**Issue by kevinkhuat** [motdotla/node-lambda#222]
Is there suppose to be a third parameter for the handler method in index.js? The hello world lambda function that AWS provides shows the following: 
`exports.handler = (event, context, callback) => {
    // TODO implement
    callback(null, 'Hello from Lambda');
};`

I was following the example from https://github.com/narainsagar/node-casperjs-aws-lambda. From the lambda testing console on AWS, I was only able to see a result in the "Execution result" area if the callback parameter was added and used.

Let me know if you guys see anything wrong and if you would want me to make any updates.

**Comment by honzie** [comment]
It seems like the `index.js` file isn't added by `node-lambda` during the setup. I used the referenced repo, https://github.com/motdotla/node-lambda-template.

Just opened a PR on that repo to include the `callback` parameter in `index.js`. It's here: https://github.com/motdotla/node-lambda-template/pull/11/files. Another issue on that repo (https://github.com/motdotla/node-lambda-template/issues/10) also references the same, which you pointed out.

**Comment by DeviaVir** [comment]
Requested maintainer status for `node-lambda-template` to get that updated at the moment (@motdotla), this is currently not something I can help with.

**Comment by motdotla** [comment]
@DeviaVir just added you. Thank you for all your hard work on node-lambda. You've done a lot for the community! 🙏

**Comment by sanathdavis** [comment]
**mark***down*
