### ISSUE TITLE
TypeError: context.done is not a function

### ISSUE THREAD

**Issue by tyshcr** [motdotla/node-lambda#223]
I am using Node v6.2.2 and the latest version of node-lambda.

I am able to run my lambda locally using `node-lambda run`, but if I use `context.succeed()` or `context.done()` I get an error in my Terminal that says:

`/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^
TypeError: context.done is not a function`

I found a similar issue from 2016 being discussed here https://github.com/motdotla/node-lambda/issues/50

**Comment by abetomo** [comment]
@tyshcr 
`Context.succeed ()` or `context.done ()` is the way Node v0.10.42 is written.
Currently supports Node.js 6.10 and Node.js 4.3 in Lambda. `Context.succeed ()` etc is deprecated in Node.js 6.10 and Node.js 4.3.
Thus, `node-lambda` stopped support for` context.succeed () `or` context.done () `.

http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-using-old-runtime.html

**Comment by tyshcr** [comment]
I see. Thank you. 

I will implement `callback(null, 'Success message')`

**Comment by ajaxsandip** [comment]
my fault was , i forgot to use path.join while using sendFile...
