### ISSUE TITLE
Deploy success with weird console output

### ISSUE THREAD

**Issue by seoker** [motdotla/node-lambda#232]
Hi,
I tried to deploy with `v0.9.0` and the result seems good except of below output:
```
=> Zip file(s) done uploading. Results follow:
{ FunctionName: 'xxxxx',
  FunctionArn: 'xxxx',
  Runtime: 'nodejs6.10',
  Role: 'xxxx',
  Handler: 'lambda.handler',
  CodeSize: 12987393,
  Description: '',
  Timeout: 259,
  MemorySize: 1024,
  LastModified: '2017-04-18T03:04:43.737+0000',
  CodeSha256: 'xxxxx',
  Version: '$LATEST',
  VpcConfig: { SubnetIds: [], SecurityGroupIds: [], VpcId: '' },
  Environment: { Variables: { LOG_ENABLED: 'true', NODE_ENV: 'default', LOG_LEVEL: 'info' } },
  KMSKeyArn: null }
=> All tasks done. Results follow:
[
 [
  [],
  []
 ]
]
```
It seems like it doesn't output the expected results in the last few lines.

**Comment by abetomo** [comment]
@seoker 
Thanks for the report.

The result of the event setting specified by `event_sources.json` is output.
If nothing is specified, it will be output as stated. So there is no problem.

Since it is not easy to understand output, I opened PR (#233).

**Comment by seoker** [comment]
Got it, thank you 👍
