### ISSUE TITLE
ENV changed for Lambda, X-Ray support label request

### ISSUE THREAD

**Issue by rbudding** [motdotla/node-lambda#241]
X-Ray provides tracing and monitoring capabilities for our Lambda functions!

It would be helpful to add an extra option in the configuration .env file for Lambda creation. 

e.g. AWS_TRACKING_CONFIG=true

for the entry: 
[--tracing-config <value>]
(AWS /reference/lambda/create-function.html)

(or did I miss something?)

**Comment by abetomo** [comment]
I opened a PR that adds an option to set it. #243
