### ISSUE TITLE
can't get excludeGlobs to work

### ISSUE THREAD

**Issue by tomazstrukeljdlabs** [motdotla/node-lambda#242]
I'm building an app that uses Nightmare, using this guide https://github.com/dimkir/nightmare-lambda-tutorial, but I'm now unable to use node-lambda for deployment.

I'm trying to exclude file electron that is originally at this path:
node_modules/nightmare/node_modules/electron/dist/electron

No matter what I input as -x argument, the file still ends here in temporary folder:
node_modules/electron/dist/electron

Even `-x "*electron*"` doesn't work .

**Comment by DeviaVir** [comment]
@tomazstrukeljdlabs it sounds like we are simply installing that package on that location (hence it's not being ignored), if this behaviour is unwanted, you can look into prebuilt packages:
https://github.com/motdotla/node-lambda#prebuilt-packages

**Comment by tomazstrukeljdlabs** [comment]
Thank you, I assumed --excludeGlobs should work also for content inside node_modules/ .
I've solved it now with this:
`./node_modules/.bin/node-lambda deploy --prebuiltDirectory . --excludeGlobs "electron/dist/*"`
