### ISSUE TITLE
If event_sources.json is not used all triggers are removed from lambda

### ISSUE THREAD

**Issue by mmustala** [motdotla/node-lambda#255]
Hi,

I noticed that when the event_sources.json is not used (file deleted and no reference to any other file with .env or -S option) the deployment removes all existing triggers from the lambda. I would expect it to skip the _updateEventSources completely when there is no input for the event sources. Then it would leave the existing triggers in place and not remove them.

If the app would receive an empty event_sources.json file then I would expect it to remove all triggers from the lambda.

What do you think?

**Comment by abetomo** [comment]
Thanks for the report.
I think that it is right, so I fixed it. (#256)
