### ISSUE TITLE
don't want always generate .env file

### ISSUE THREAD

**Issue by seoker** [motdotla/node-lambda#262]
Currently, this program always generates `.env` while archiving and deploying which is not what I expect.

I would manually specify `AWS_PROFILE`, `AWS_ROLE_ARN`, `AWS_ENVIRONMENT`, ... these variables through my deploy scripts and I have separate env files for different environment. Always generate a sample file `.env` doesn't fit my scenario.

Though I can put the file into `.gitignore`, seeing the unexpected file being generated under the project root folder still kinda annoys me. Is it possible not to generate the file?

**Comment by DeviaVir** [comment]
We should only be generating `.env` (and other files) when running `node-lambda setup`, do you see these files created when running other commands?

**Comment by seoker** [comment]
@DeviaVir Yes, the `.env` was generated when I run `node-lambda deploy`
I guess the file might be written by [this statement](https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L482)

**Comment by ColinEberhardt** [comment]
@seoker I think you might mean this statement: https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L486

**Comment by seoker** [comment]
@ColinEberhardt Yes, exactly. The line has been shifted lol

**Comment by abetomo** [comment]
I seemed there was no need to `_createSampleFile` on `_buildAndArchive` so I opened PR(#270).
