### ISSUE TITLE
event.json should accept array

### ISSUE THREAD

**Issue by demian85** [motdotla/node-lambda#283]
Is there a away to allow `event.json` file to have an array of events instead? I just want to test many cases with a simple command.
The only way I came up with is to manually execute `run` cmd passing different files as parameters.

Thanks.

**Comment by abetomo** [comment]
@demian85 

How about in a corresponding way with `npm run` or shell script?

Prepare an event file with a certain rule. (Such as event_test1.json, event_test2.json, ...)
There is a way to make the following shell script which executes those files serially.
```bash
for eventfile in event_test*.json; do node-lambda run -j ${eventfile}; done
```

Also, if you write similar contents in package.json you can do it with `npm run`.
```json
...
  "scripts": {
    ...
    "multipleEventsTest": "for eventfile in event_test*.json; do node-lambda run -j ${eventfile}; done"
  },
...
```

```bash
$ npm run multipleEventsTest
```

**Comment by DeviaVir** [comment]
Closing due to no response registered after a possible solution has been offered. Feel free to comment in case the issue persisted.

**Comment by demian85** [comment]
Yeah it woks, but would be cleaner if `event.json` accepts an array of events, or perhaps add `events.json` as another feature.

**Comment by abetomo** [comment]
@demian85 
If there is an array in event.json, we modified it to treat it as multiple events. #311
