### ISSUE TITLE
after update... I can not package or deploy anymore. node-lambda/lib/main.js:709

### ISSUE THREAD

**Issue by rbudding** [motdotla/node-lambda#290]
Did an update, now to version .10.

After the node-lambda package or deply statement I get: 

/usr/local/lib/node_modules/node-lambda/lib/main.js:709
      throw err;
      ^

Error: Command failed: npm -s install --production --prefix /Users/../BF_S3_Dynamo_dashboard/.lambda 

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

--> The .lambda folder is created and files are copied for packaging..

**Comment by abetomo** [comment]
@rbudding 
When running node-lambda package or deploy, run npm install during the process.
It seems that it has failed.
Would you please give the result of the following command which is also in the error message if possible?

```
npm install --production --prefix /Users/../BF_S3_Dynamo_dashboard/.lambda
```

**Remove and execute the `-s` option. Then an error message will be displayed **

**Comment by DeviaVir** [comment]
@rbudding did the feedback above help to resolve your issue?

**Comment by DeviaVir** [comment]
Closing due to no response registered. Feel free to comment in case the issue persisted.

**Comment by ARAtlas** [comment]
I'm a new user and just started with version .10. I have the same problem as described above. I ran the line without "-s" as suggested above. Here was the output:

```
npm install --production --prefix /Users/atlas/Documents/Clients/Volley/Skills/Yes Sire/yes-sire-game/.lambda
npm ERR! addLocal Could not install /Users/atlas/Documents/Clients/Volley/Skills/Yes Sire/yes-sire-game/Sire/yes-sire-game/.lambda
npm ERR! path /Users/atlas/Documents/Clients/Volley/Skills/Yes Sire/yes-sire-game/Sire/yes-sire-game/.lambda
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/atlas/Documents/Clients/Volley/Skills/Yes Sire/yes-sire-game/Sire/yes-sire-game/.lambda'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/atlas/.npm/_logs/2017-05-30T18_48_13_620Z-debug.log
```

I notice that the path listed in the error is suspect. The correct path to the .lambda folder is:

```
/Users/atlas/Documents/Clients/Volley/Skills/Yes Sire/yes-sire-game/.lambda
```

While the path listed in the error message is wrong:

```
/Users/atlas/Documents/Clients/Volley/Skills/Yes Sire/yes-sire-game/Sire/yes-sire-game/.lambda
```

Specifically, the path listed in the error message has an extraneous "/Sire/yes-sire-game" inserted into it.

**Comment by ARAtlas** [comment]
Note that one of my folders "Yes Sire" has a space in it. I think you need to wrap the path you provide to NPM in quotes.

**Comment by abetomo** [comment]
@ARAtlas Fixed. (#303)
