### ISSUE TITLE
How to use Proxy

### ISSUE THREAD

**Issue by komikoni** [motdotla/node-lambda#296]
Thank you for a useful tool.
It is necessary to patch main.js as follows.

```javascript
var proxy = require('proxy-agent');
aws.config.update({
  httpOptions: { agent: proxy('http://hogehoge.com:8080') }
});
```

**Comment by DeviaVir** [comment]
This looks like a very specific usecase, and not something we can accept as a PR or feedback. If I'm wrong feel free to comment and enlighten us with your views.

**Comment by abetomo** [comment]
@komikoni Proxy is now available.
#322#issuecomment-308967790
