### ISSUE TITLE
AWS console environmental variables persist

### ISSUE THREAD

**Issue by nonword** [motdotla/node-lambda#297]
I suspect this is a AWS console bug, but: Has anyone noticed that environmental variables set using the AWS console do not *appear* to be overwritten by `node-lambda deploy -f deploy.env`?

For example, if I:
 * In the AWS console: Set "FOO" = "manual-value"
 * Use node-lambda to deploy with a `deploy.env` containing "FOO=deployed-value"

The deployed lambda operates with `process.env['FOO'] === 'deployed-value'` **but** the AWS console shows the old "manual-value". It's as if the AWS console only knows about variables established through the AWS console. 

On the off-chance I'm just deploying incorrectly, I'm posting here. Has anyone seen this?

**Comment by abetomo** [comment]
@nonword 
Do you know the version of `node-lambda`?
It is possible that you are using the old `node-lambda`.

If it is the latest node-lambda, I think that it will work as expected in `node-lambda deploy -f deploy.env`.

**Comment by DeviaVir** [comment]
Closing due to possible answer suggested and no response registered. Feel free to comment and we can re-open in case this issue persisted.
