### ISSUE TITLE
Docker image option doesn't work because npm install is run in the wrong directory

### ISSUE THREAD

**Issue by itsMichaelBates** [motdotla/node-lambda#314]
I'm trying to get the `DOCKER_IMAGE` environment variable/command line argument to work with an existing docker image I have (of Amazon Linux, to compile platform specific binaries).

However, because the project's files are mounted in `/var/task`, and Docker by default launches in `/` the npm install command fails (because no `package.json` exists in `/`).

Any ideas how to get around this?

**Comment by itsMichaelBates** [comment]
This could probably be solved by adding `--prefix /var/task` to `npm install` (full command would be `npm -s install --production --prefix /var/task`)?

**Comment by abetomo** [comment]
@itsMichaelBates Could you tell me the option of the node-lambda command you ran and the error that was output?

**Comment by nmaves** [comment]
I just tried this command and it failed.

```
node-lambda package -I lambci/lambda:nodejs6.10 -H nightlyCleanup.handler

**Comment by abetomo** [comment]
@nmaves 
Could you tell us the directory structure that can be presented, such as the directory where the `npm run package:cleanup` command was executed and the location of the packaging target directory?

**Comment by nmaves** [comment]
Hre you go!

```
-rw-r--r--@   1 nmaves  staff   1.1K Jul 26 22:04 README.md
drwxr-xr-x@   3 nmaves  staff   102B Jan 20  2017 build
-rw-r--r--@   1 nmaves  staff     3B Jan 20  2017 context.json
-rw-r--r--@   1 nmaves  staff    28B Jan 20  2017 deploy.env
-rw-r--r--@   1 nmaves  staff     4B Mar 20 23:29 event.json
-rw-r--r--@   1 nmaves  staff   275B Mar 13 20:14 initialImport.js
-rw-r--r--@   1 nmaves  staff   3.8K Mar 21 00:21 mysqlUpdate.js
-rw-r--r--@   1 nmaves  staff   3.8K Mar 25 12:20 neighborhoodUpdate.js
-rw-r--r--@   1 nmaves  staff   6.3K Jul 27 08:49 nightlyCleanup.js
drwxr-xr-x  176 nmaves  staff   5.8K Jul 26 21:43 node_modules
-rw-r--r--@   1 nmaves  staff    63K Jul 26 21:43 package-lock.json
-rw-r--r--@   1 nmaves  staff   729B Jul 26 22:03 package.json
-rw-r--r--@   1 nmaves  staff   3.2K Mar 20 23:32 retsQuery.js
-rw-r--r--@   1 nmaves  staff   2.7K Mar 12 11:13 tableDuplicator.js
```

**Comment by abetomo** [comment]
@nmaves 
Thank you.
I made a similar directory structure and confirmed it.
But since the error does not reproduce, I will investigate a little more.

**Comment by nmaves** [comment]
Let me know how I can help.

**Comment by abetomo** [comment]
@nmaves Looking at the error message, it seems to be an error issued by Node.js.
What version of Node.js is used?

**Comment by nmaves** [comment]
Looks like I am running v8.1.0

**Comment by abetomo** [comment]
I created a simple project on the Mac and checked the operation, but no error occurred.
It is difficult to respond if the error does not reproduce.

I ran it in the following environment. (node-lambda is 0.11.3.)
```
% node -v
v8.1.0
% docker -v
Docker version 17.06.0-ce, build 02c1d87
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```
Is there anything you care about the environment?

**Comment by deedw** [comment]
I have submitted pull request #381 that fixes this by adding the `-w /var/task` option to the docker run command
