### ISSUE TITLE
Deploy behind a corporate proxy

### ISSUE THREAD

**Issue by perevernihata** [motdotla/node-lambda#322]
Hi guys, here is what I'm getting while trying to deploy lambda function: 
```
connect ETIMEDOUT 13.55.205.119:443
=> Retrying
connect ETIMEDOUT 13.55.205.119:443
=> Retrying
connect ETIMEDOUT 52.63.216.104:443
=> Retrying
connect ETIMEDOUT 52.63.216.104:443
=> Retrying
C:\Users\user\Documents\my-lambda-function\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

Error: connect ETIMEDOUT 52.63.216.104:443
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1073:14)
```
I'm 99% sure that this is because I'm trying to do that from behind a corporate proxy. According to aws-sdk docs http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html I suppose to configure proxy setting using code bellow:

```
var proxy = require('proxy-agent');
    
    AWS.config.update({
      httpOptions: { agent: proxy('http://internal.proxy.com') }
    });
```

But I'm not sure where to plug this code in, and do not see any parameter which supposed to support handling proxies in your node-lambda. Would appreciate any ideas.

**Comment by DeviaVir** [comment]
You can now deploy with `-y "http://internal.proxy.com"` on latest master, thanks to @abetomo for implementing and thanks for suggesting this!
