### ISSUE TITLE
Multiple Lambdas in project

### ISSUE THREAD

**Issue by tgig** [motdotla/node-lambda#33]
Hey, really like what you've done here. Very elegant solution.

I'd like to update the code a bit to support optional folders with Lambdas inside of them, but still use the simple commands you've laid out for running/deploying.

I.e., right now, only one Lambda per project is supported. I'd like to be able to have many Lambdas in subfolders. My code will not modify the default structure, just support the new optional subfolder structure.

E.g., it would go from only supporting this:

```
/index.js
/event.json
```

To also supporting this:

```
/index.js
/event.json
/module1/index.js
/module1/event.json
/module2/index.js
/module2/event.json
...
```

And you would be able to run the Lambda in the subfolder by passing in an optional 

```
./node_modules/.bin/node-lambda run --directory module1
```

Sound like a worthwhile Pull request to you?

**Comment by motdotla** [comment]
@tgig very cool idea, but I would recommend you create it as a separate repo that uses node-lambda as a dependency. I'd be happy to link to it from the README.

**Comment by lpil** [comment]
Heya. Did this get implemented?

**Comment by motdotla** [comment]
It looks like not yet @lpil. My recommendation was to link to it when @tgig created it.

**Comment by lpil** [comment]
Thanks.

**Comment by tgig** [comment]
Sorry guys, the core node-lambda code was not compatible with what I needed
to do. I ended up writing a couple of my own (albeit, less powerful)
scripts to fill my needs.
