### ISSUE TITLE
No longer preserves permissions with v0.11.0

### ISSUE THREAD

**Issue by Tarang** [motdotla/node-lambda#333]
If a npm module has a file in it, node-lambda wont preserve these permissions when uploading files.

#### Reproduction:
Have a file in a project with `0755` permissions create a deployment (fetch from lambda)/zip file

#### Results:
Version 0.10.0 (installed with `npm install node-lambda@0.10.0 -g` has the correct permissions (0755)
Version 0.11.0 has the incorrect permissions (0664)

#### End result:
Projects with binary files will have EACCS errors while running spawn to a child process, which is unexpected.

**Comment by abetomo** [comment]
Please wait for about three days as I will check and respond.
(If there is someone who can respond more quickly, please take measures.)

**Comment by bluepeter** [comment]
Experiencing this problem too trying to spawn a phantomjs process.

**Comment by abetomo** [comment]
I fixed bugs and opened PR. #335
