### ISSUE TITLE
multiple functions per repo

### ISSUE THREAD

**Issue by ksnyde** [motdotla/node-lambda#34]
I'm creating a set of related micro-services and would like them all to live under a single git repo. Possibly this is a false hope but is there any way to have subdirectories in a repo (each with a `package.json` in it) that would work with `node-lambda`? 

When I try it now it traverses up to the root of the git repo instead of to the micro-services subdirectories.

**Comment by ksnyde** [comment]
nevermind, i need sleep

**Comment by cspeer** [comment]
@ksnyde I need sleep too. Could you let me know how you did it?

**Comment by ksnyde** [comment]
So my original strategy was to have a master repo with "sub-projects" in it. I know that the latest release of git supposedly gives sub-projects some needed improvements but for a variety of reasons this didn't work very well for me. It _can_ work though, you just need individual `package.json` files for each micro-service (as you'd expect) and ensure you're in the root of the sub-project when you deploy using **node-lambda**.

I'm now just using seperate repos for each microservice and if there's any shared functionality i just make it a common library and "require" it.

Make sense? Hope you get some sleep @cspeer

**Comment by cspeer** [comment]
Thanks a lot @ksnyde , I was hoping to somehow avoid having multiple `package.json` files, and magically feed them all from just one `node_modules` like serverless.com does.
I think I will have to go with another strategy here, because I got a lot of functions that all require common modules and having to set up each and everyone of them with its own package.json sounds like an overkill.

**Comment by ksnyde** [comment]
Could you not have a entry handler that takes all requests and then proxies that onto the message handler you need? That might also have the benefit of greater caching on AWS and therefore shorter startup time?

-- 
Ken Snyder

On 23 June 2016 at 10:16:51 p, Christopher Speer (notifications@github.com) wrote:

Thanks a lot @ksnyde , I was hoping to somehow avoid having multiple package.json files, and magically feed them all from just one node_modules like serverless.com does.
I think I will have to go with another strategy here, because I got a lot of functions that all require common modules and having to set up each and everyone of them with its own package.json sounds like an overkill.

**Comment by cspeer** [comment]
I suppose I could. If I understand you correctly: let's assume I have some complex and/or high intensity functions. If I was to route everything through one handler I'd be unable to give certain functions more memory or a longer/shorter timeout to optimize the function.
It would certainly help with caching and startup time, though.
