### ISSUE TITLE
Specifying --mode request results in enum error 

### ISSUE THREAD

**Issue by ZiadHilal** [motdotla/node-lambda#35]
During deployment, add the argument --mode request and you'll get this error:

> [ValidationException: 1 validation error detected: Value 'request' at 'mode' failed to satisfy constraint: Member must satisfy enum value set: [event]]

However, setting the mode to "request" in the .env file works. I'm pretty sure the cli arg should also support "request", not just "event".

**Comment by mbbernstein** [comment]
I'm having the same issue:
This is from the aws-sdk as you can see in https://github.com/aws/aws-sdk-js/blob/7d02a64bc559a0edba3799dae42a3f964cfb9c28/apis/lambda-2014-11-11.normal.json#L712

**Comment by DeviaVir** [comment]
Mode is no longer a thing in new API:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html
And even when it was supported, it would only understand `event` (like in previous API, 2014, currently on this master).

**Comment by DeviaVir** [comment]
Mode is now gone:
https://github.com/motdotla/node-lambda/commit/a8e27ca19f9e1ee0180a7e7581ff447994827a59#diff-de85a0cb894422994a1df4730da54144L18
