### ISSUE TITLE
Package relative dependencies

### ISSUE THREAD

**Issue by wawanco** [motdotla/node-lambda#354]
Hi!

I have the following project structure 
```
myproject/
   ./lambda1
   ./common
```

`common` being a common library used by lambda1 and potentially other lambdas in the same project.

In `lambda1/package.json`, I add the following lines

```
"dependencies": {
    "common": "file:..\\common"
  }
```

When I run `node-lambda package` it seems that the `lambda1/package.json` is copied as is in `.lambda/package.json`, but the relative path is no more correct and the packaging fails with this error

```
Error: Command failed: cmd.exe /c npm -s install --production --prefix C:\myproject\lambda1\.lambda --cwd C:\myproject\lambda1\.lambda
```

os: *Windows 7*
npm: *v3.10.10*
node-lambda: *v0.11.3*
node: *v6.11.0*

Any clue ?

**Comment by abetomo** [comment]
Is it possible to make the `common` path specification of package.json an absolute path rather than a relative path?

**Comment by abetomo** [comment]
I'm sorry. It was useless to make it an absolute path.

**Comment by abetomo** [comment]
Is it possible to place `common` under `lambda1` and make it `"common": "file:common"`?

**Comment by wawanco** [comment]
1. Yes with an absolute path it works but I'd like to share my code with other folks so it doesn't seem to be a good solution
2. If I place `common` under `lambda1`, what if I have a `lambda2` that also uses `common` ?

I suppose that the right solution should be to resolve the relative paths in `package.json` to absolute paths when the package is created. In other word, we let the `myproject\package.json` untouched and the `myproject\.lambda\package.json` is edited during the `node-lambda package` process. What do you think ?

**Comment by abetomo** [comment]
Could you try the `--prebuiltDirectory` option?
`node-lambda package --prebuiltDirectory .`

**Comment by wawanco** [comment]
It works! Thanks for your answer!

**Comment by GauntStrelok** [comment]
Hey, i have a similar structure, how to exactly write the command? i'am inside lambda1 folder, and i run node-lambda package --prebuiltDirectory ../common

and in .lambda it builds the common and the lambda1, is ok that?

**Comment by abetomo** [comment]
@GauntStrelok  Running in `node-lambda package --prebuiltDirectory ../common` will only include `common`.

If you want to build with `lambda1` and `common` you should prepare `package.json` like this issue.
