### ISSUE TITLE
Arrays as arrays

### ISSUE THREAD

**Issue by yeehaa123** [motdotla/node-lambda#371]
Currently, arrays are interpreted as a sequence of events. However, there’s no way to use normal array events anymore. This is particularly a problem when working with step function and its parallel states (they return arrays). Also, interpreting arrays as sequences does not conform to the aws event specs. Would it be possible to add a flag that turns this behavior on or off?

**Comment by abetomo** [comment]
@yeehaa123 O.K.
Add an option.

**Comment by yeehaa123** [comment]
@abetomo I would be happy to help out with this if you like. But I would need some guidance where to start, and which files the change would involve.

**Comment by abetomo** [comment]
opened #372
