### ISSUE TITLE
-T appears twice in deploy command options

### ISSUE THREAD

**Issue by briely** [motdotla/node-lambda#384]
It seems the deploy command uses `-T` for both `--tracingConfig` and `--deployTimeout`.

https://github.com/motdotla/node-lambda/blob/master/bin/node-lambda#L85
https://github.com/motdotla/node-lambda/blob/master/bin/node-lambda#L99

**Comment by abetomo** [comment]
@briely 
Thank you for the report.
Are there already PR preparations?
If not I will fix it.

**Comment by briely** [comment]
No. Not yet.
