### ISSUE TITLE
Unable to run locally from behind a proxy server

### ISSUE THREAD

**Issue by pritpalchahal** [motdotla/node-lambda#388]
I am able to deploy from behind a proxy using the -y flag on deploy command. But I cannot run locally from behind a proxy. Is it possible to also implement a similar flag for run command too. I could have made that change but I don't have the permission to contribute. Thanks.

**Comment by DeviaVir** [comment]
What do you mean that you do not have the permission to contribute? You can fork and then PR your changes.

**Comment by DeviaVir** [comment]
Merged the PR!
