### ISSUE TITLE
s3:ObjectCreated:* eventsource?

### ISSUE THREAD

**Issue by vekexasia** [motdotla/node-lambda#391]
I'm trying to add s3:ObjectCreated:* event trigger for my lambda function using event_source but I can't get it working.

whatever i try, even with arn:aws prependend will return the following error.
``` 
validation error detected: Value \'s3:ObjectCreated:*\' at \'eventSourceArn\' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\\-])+:([a-z]{2}(-gov)?-[a-z]+-\\d{1})?:(\\d{12})?:(.*)
```

**Comment by abetomo** [comment]
@vekexasia We do not support S3 events, so we need to add functionality.

Could you show me what kind of event_source.json you created?
I would like to use it for implementation.

**Comment by vekexasia** [comment]
@abetomo I tried several stuff but nothing worked so i totally removed it. Do you recommend using something else for registering the lambda to s3 events? Maybe aws -cli?

**Comment by abetomo** [comment]
@vekexasia Thank you for your reply.
OK. I will be working from now so I think I can support S3 event next week.
I think it is better to use aws-cli.

**Comment by vekexasia** [comment]
Hello @DeviaVir do you think it would be possible to deploy the version  to npm? tkz.

**Comment by DeviaVir** [comment]
@vekexasia https://github.com/motdotla/node-lambda/releases/tag/0.11.5 + https://www.npmjs.com/package/node-lambda 0.11.5 available now, which includes this.

**Comment by DeviaVir** [comment]
as an aside, note that NPM supports pointing to a specific commit, so you don't have to wait for releases.
```
"dependencies": {
  "package": "git://github.com/username/package.git#commit"
}
```

or

```
npm install maintainer/package#commit
```
