### ISSUE TITLE
Request: node-lambda run to auto stringify event body

### ISSUE THREAD

**Issue by dan-kez** [motdotla/node-lambda#411]
Hello!

It would be very helpful if there was a way for node-lambda to automatically stringify the event body similar to what the API-Gateway does.

At present, I have to write my body payload as escaped json so that I can emulate the input that the API gateway will send.

Best,
Daniel

**Comment by lubiepomaranczki** [comment]
@dan-kez could you please write how do you emulate API gateway? It would help a lot of people ;-)

**Comment by abetomo** [comment]
Fix to emulate only the body of the API Gateway event.
#530
