### ISSUE TITLE
passing in --version doesn't work

### ISSUE THREAD

**Issue by theambidextrousboy** [motdotla/node-lambda#42]
Not sure if i'm using it correctly or not, but if i try to pass in a value for --version it will just bring up the version of node-lambda not actually set the version of the lambda job on AWS

**Comment by motdotla** [comment]
@theambidextrousboy can you paste the full command you are typing into the terminal? (scrubbing any sensitive data). I'll take a look

**Comment by faceleg** [comment]
```
node-lambda deploy --version '1.2.1'
```

That outputs node-lambda's version and exits

**Comment by jkervine** [comment]
Seems to me that using:

`node-lambda deploy -v 1`

Starts to append a new "version", but what it does it just appends the version number and creates a new lambda function, called "functionName-1".

**Comment by jkervine** [comment]
Which, I now see, is the beef of https://github.com/motdotla/node-lambda/issues/49. Sorry for not looking through whole list before commenting...
