### ISSUE TITLE
Unable to create multiple s3 trigger events for the same bucket.

### ISSUE THREAD

**Issue by xostap** [motdotla/node-lambda#422]
Hi there,

I'm having an issue deploying multiple s3 trigger events for the same bucket.

**Current Results:**
-----------------
When using **evet_sources.json** with **eventSourceFile** flag combination for deployment, only one of the s3 events listed in S3Events array (see below) will be created. 

**Expected Result:**
-----------------
The expectation is that user should be able to create multiple s3 triggers events for the same bucket if filter rules are different. It is currently possible to create manually multiple s3 trigger events using AWS Lambda console (UI) for the same bucket.

**Here is deploy command example:**
-----------------------
`node-lambda deploy --configFile <SECRET_VARIABLES_FILE_US> --region us-east-1 --environment <ENV> --eventSourceFile <EVENT_SOURCES_FILE_US>`

**Here is "evet_sources.json" file contents:**
-----------------------------------------

```json
{
  "S3Events": [
    {
      "Bucket": "dev-jobs",
      "Events": [
        "s3:ObjectCreated:*"
      ],
      "Filter": {
        "Key": {
          "FilterRules": [
            {
              "Name": "prefix",
              "Value": "router/input"
            },
            {
              "Name": "suffix",
              "Value": ".json"
            }
          ]
        }
      }
    },
    {
      "Bucket": "dev-jobs",
      "Events": [
        "s3:ObjectCreated:*"
      ],
      "Filter": {
        "Key": {
          "FilterRules": [
            {
              "Name": "prefix",
              "Value": "router/output"
            },
            {
              "Name": "suffix",
              "Value": ".json"
            }
          ]
        }
      }
    }
  ]
}
```

**Comment by abetomo** [comment]
Thanks for the report.
It was a bug. I will fix it now.
