### ISSUE TITLE
make exclude files config external

### ISSUE THREAD

**Issue by sabrinaluo** [motdotla/node-lambda#44]
Currently we need to edit  ./lib/main.js to exclude the file we don't want to deploy.

can you make it works like .gitignore?
when first creating a aws-lambda project, run ```node-lambda init```, it will create a .xxignore file, so that we can exclude the files we don't want to deploy. 

thank you :)

**Comment by motdotla** [comment]
Nice suggestion.

Related: https://github.com/motdotla/node-lambda/pull/48 and https://github.com/motdotla/node-lambda/pull/43
