### ISSUE TITLE
Feature request: upload to s3 and deploy from bucket

### ISSUE THREAD

**Issue by teebu** [motdotla/node-lambda#444]
Same thing to what it's doing now, but instead of sending the zip directly to AWS lambda, it first uploads it to a predefined bucket/key(prefix) and deploys from s3. 

Advantage: size limits seem to be much higher when deploying from s3, 250meg zips, vs direct zip upload which is limited to 50megs.

**Comment by abetomo** [comment]
I think that it is useful to upload it to S3 and deploy it.
However, I think that the upper limit of the zip file size does not change even if uploading to S3.
250 MB seems to be the size of the code before compression.

https://docs.aws.amazon.com/lambda/latest/dg/limits.html
[AWS Lambda Deployment Limits]

**Comment by teebu** [comment]
https://hackernoon.com/exploring-the-aws-lambda-deployment-limits-9a8384b0bec3

It's been tested, and I can confirm.

**Comment by abetomo** [comment]
Thanks for sharing information.

**Comment by abetomo** [comment]
Add the function to deploy from S3.
Please wait for a few days before opening the PR.
