### ISSUE TITLE
Specify event source?

### ISSUE THREAD

**Issue by noqcks** [motdotla/node-lambda#45]
Is there a way to specify an event source for the lambda script using node-lambda? There is just `AWS_MODE=event` afaik. 

For example, I would like to specify an S3 event for my lambda script to run when `.json` gets created in bucket `random-bucket`. Is there a way to specify this with node-lambda?

**Comment by craigsketchley** [comment]
+1

**Comment by DeviaVir** [comment]
I understand the use-case, but this doesn't actually happen on the lambda side so much (except for adding permissions). For a resource, see: http://docs.aws.amazon.com/lambda/latest/dg/with-s3-example-configure-event-source.html
