### ISSUE TITLE
error when using S3 to deploy with multiple AWS_REGION set

### ISSUE THREAD

**Issue by teebu** [motdotla/node-lambda#453]
Setting: `AWS_REGION=us-east-1,us-west-1`

us-east-1 deploys, but throws error when trying to deploy the second lambda to us-west-1.

```
Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: us-east-1. Please use this region to retry the request
```

The issue isn't the multiple regions, but the bucket is in `us-east-1` and when trying to deploy to `us-west-1` it tries to use the west bucket. 

Probably the solution is to add `DEPLOY_S3_REGION` parameter,

**Comment by abetomo** [comment]
S3 and Lambda seem to need to be in the same region.
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html

We have to create a bucket for the deployed region.
I think that I can fix it by this week.
