### ISSUE TITLE
The new deploy to s3, specify your own deploy bucket

### ISSUE THREAD

**Issue by teebu** [motdotla/node-lambda#456]
The new s3 deploy doesn't give you an option to deploy from a specific bucket, and creates a bucket for each function, this could get messy if you have a lot of functions. 

I liked the ability to specify the bucket and key (maybe prefix option), because I use an IAM user with permissions to a specific deploy bucket.

So, there should be an option to specify the deploy bucket.

**Comment by abetomo** [comment]
You need to specify the bucket name for each target region.
I did not know the optimal way to specify the region and bucket name pair, so I created it automatically.
Please give me your advice if you have any ideas.

**Comment by teebu** [comment]
There really is no best way to do it, beside specifying the bucket per region in a config. 

`S3_USEAST1_BUCKET:east-deployer`
`S3_USEAST2_BUCKET:east-2-deployer`

It's really dumb that Amazon doesn't let you deploy a lambda from S3 from any region if they're just using it as a data store. That is something we might have to ask / request from them.
