### ISSUE TITLE
Deploy fails on Windows due to missing rsync

### ISSUE THREAD

**Issue by VaclavSynacek** [motdotla/node-lambda#47]
Executing external `rsync` during deploy fails on Windows (without cygwin).

**Comment by StoneCypher** [comment]
I just deployed from Windows, and I don't have `rsync` installed.

**Comment by StoneCypher** [comment]
I did, however, have to install `infozip` to get a zip/unzip impl which honored the unix-style flags.

**Comment by StoneCypher** [comment]
Ok, this seems to be because `rsync` is installed locally as a dep, in a way that a global install will not pick up in path.  If you install `node-lambda` locally rather than globally, it should begin to work.

This is a bug.

**Comment by motdotla** [comment]
Thanks for investigating this. I'm giving this lib some :heart: this weekend, so I'll try and slot it in then.

**Comment by bbodenmiller** [comment]
I'm also unable to get deploy to work on Windows - appears to be an `rsync` issue. I tried installing rsync using NPM, no luck.

**Comment by teebu** [comment]
my solution was to use ncp module.

**Comment by martindavid** [comment]
is anyone figure this out?? I'm also having the same problem here. I use Windows 10

**Comment by teebu** [comment]
you can use my fork, its a little different, but works for what I need. It uses npc and 7zip on windows. 
https://github.com/teebu/node-lambda

**Comment by DeviaVir** [comment]
Now Bash on Windows is a thing, these Windows issues don't seem so important anymore.
http://www.zdnet.com/article/ubuntu-and-bash-arrive-on-windows-10/

**Comment by StoneCypher** [comment]
If you'd just install node-lambda as a local dep, it'd be fixed, and you wouldn't have to close it unfixed

Most people won't move their existing tooling to the bash shell, esp. VC users with big existing stacks
