### ISSUE TITLE
VPC ID is missing

### ISSUE THREAD

**Issue by demian85** [motdotla/node-lambda#478]
How can I deploy using VPC settings if there is no option to set the VPC ID?

From AWS SDK docs:
```
VpcConfig — (map)
The function's networking configuration.

SubnetIds — (Array<String>)
A list of VPC subnet IDs.

SecurityGroupIds — (Array<String>)
A list of VPC security groups IDs.

VpcId — (String)
The ID of the VPC.
```

So, all we have is
``` 
AWS_VPC_SUBNETS="subnet-f2b579af (172.31.32.0/20) | us-east-1a,subnet-bf3df5db (172.31.0.0/20) | us-east-1b"
AWS_VPC_SECURITY_GROUPS="sg-84fd39f2"
``` 

Which, btw, I cannot guess the correct identifier for each one of those subnets. Every one of them is an endless string.

**Comment by DeviaVir** [comment]
Try with:
```
AWS_VPC_SUBNETS="subnet-f2b579af,subnet-bf3df5db"
AWS_VPC_SECURITY_GROUPS="sg-84fd39f2"
```

**Comment by demian85** [comment]
but where is the vpc id? there should be 3 required parameters, vpc id, vpc subnets and vpc security groups.

**Comment by DeviaVir** [comment]
Subnets belong to a VPC, so supplying a VPC is not required.

**Comment by demian85** [comment]
good, it worked 👍
