### ISSUE TITLE
"deploy --packageDirectory" behavior

### ISSUE THREAD

**Issue by SergeyAvd** [motdotla/node-lambda#483]
What's the expected behavior of `node-lambda deploy --packageDirectory dir_name`?

I'm confused about what it is supposed to do when used with `deploy`.

My original idea was that it takes the output zip of `node-lambda package` and deploys it to AWS.

But I've tried it a couple of times and from the console output I see it never skipped the packaging step.

The second idea was that it leaves the package being deployed in that folder. That didn't check out either.

So, my question is what is it supposed to do? And how to use it? Any example use cases would be really helpful.

Thanks!

**Comment by abetomo** [comment]
`packageDirectory` did not work in 'deploy'.
If you want to use the created zip file, you can use the `-z, --deployZipfile [DEPLOY_ZIPFILE]` option.

**Comment by SergeyAvd** [comment]
@abetomo Thank you for your reply!

Are you saying it is not supposed to work at all in 'deploy'? Or there was an idea what it should do, but that was not implemented yet?

**Comment by abetomo** [comment]
@SergeyAvd `packageDirectory ` was a meaningless option that does nothing in deploy.
So I opened PR to remove that option.
