### ISSUE TITLE
Please update npm package to support 10.x

### ISSUE THREAD

**Issue by fogfish** [motdotla/node-lambda#491]
```bash
nmp install -g node-lambda

...
node-lambda run
Runtime [nodejs10.x] is not supported.
```

**Comment by fogfish** [comment]
npm is still hosting [0.13.0](https://www.npmjs.com/package/node-lambda). 
Would you be able to publish changes today/tomorrow ?

**Comment by DeviaVir** [comment]
Sorry about that, usually [this job](https://travis-ci.org/motdotla/node-lambda/jobs/537722333) does it for us. Published it manually just now.

**Comment by fogfish** [comment]
thank you! I think this is a caching issue at npmjs site.
