### ISSUE TITLE
-A/--tags Option Not Working

### ISSUE THREAD

**Issue by maggie9595** [motdotla/node-lambda#517]
```
$ /home/circleci/project/node_modules/.bin/node-lambda deploy -G ./http_headers -o ************************************************************* -m 128 -t 3 -H lambda.handler -u nodejs10.x -p true -n lambda_name --tags tag1=value1
error: unknown option `--tags'
```

I am on v0.14.0 and -A and --tags both give me the unknown options error.

**Comment by DeviaVir** [comment]
Indeed, we haven't cut a release in a while. Tags has been added to master since 0.14.0. I'll create one.

**Comment by DeviaVir** [comment]
https://github.com/motdotla/node-lambda/releases/tag/0.16.0 is now available.

**Comment by maggie9595** [comment]
Thank you @DeviaVir!! Does it need to be published on NPM too?

**Comment by DeviaVir** [comment]
Sorry, done.

**Comment by maggie9595** [comment]
Thank you for the quick turnaround :) tags are working on 0.16.0 now!
