### ISSUE TITLE
The operation cannot be performed at this time. An update is in progress.

### ISSUE THREAD

**Issue by vikash-aquera** [motdotla/node-lambda#535]
Hi team,
when we try to update lambda using your API using the latest version of the node -lambda there is an issue while deployment.
The issue will call when you try to update VPC config as well while updating your code.
We debug our cloud trail and found issue is coming because of the subsequential call of two API without finishing the first one.

the deployment process would start with an UpdateFunctionCode API call first followed by an UpdateFunctionConfiguration API call, while the recent deployments that fail start with the UpdateFunctionConfiguration and follow with the UpdateFunctionCode API call. This is causing the ResourceConflictException error because UpdateFunctionConfiguration can take a minute to finish because the configurations has VPC resources[2], with the UpdateFunctionConfiguration call just before the event

This will cause the subsequent UpdateFunctionCode API call to fail with the "ResourceConflictException" as it is made immediately while the UpdateFunctionConfiguration  API call has not finished. 

Our production env got down because of this. Very critical for us. Please fix asap.

**Comment by vj-raghavan** [comment]
@vikash-aquera we have the same issue in our project. So in your pipeline or in your CD solution you could just install node-lambda version 0.16.0 and that solved the issue for us. 

Is this a good first issue to be picked up and fix ? I would like to give a helping hand if possible.

**Comment by ErizonEE** [comment]
Hi team, 

This behavior happens updating environment vars too.

Thanks so much for sharing your work.

Regards,

**Comment by HenriqueFadoni** [comment]
I am having the same problem with my project. To be honest, I am using AWS Amplify to host a NextJs 11 ( SSG ) application, for some reason when I try to call my graphql server hosted on EC2. It displays this error: 

 ResourceConflictException: The operation cannot be performed at this time. The resource arn:aws:lambda:--------:-------------------:function:foztgnt-pwpurgm is currently in the following state: 'Pending'. StateReasonCode: 'Creating'

**Comment by jmouka** [comment]
I'm also seeing this issue, using node-lambda 0.19.0. Any ideas on a fix?

**Comment by DeviaVir** [comment]
Closing, feel free to leave a comment if this still occurs in recent versions.

**Comment by noslouch** [comment]
fwiw i'm seeing this on `0.22.0`
