### ISSUE TITLE
package.json "main" field seems ignored

### ISSUE THREAD

**Issue by justin-souter** [motdotla/node-lambda#55]
The run command still seems to look for index.js even though I've set the "main" field in the package.json file to something other than index.js. Renaming the main.js file to index.js allowed it to run, without changing the "main" field.

**Comment by coagmano** [comment]
node-lambda uses the `AWS_HANDLER` setting in `.env` to determine what to run, as that's what AWS use on lambda.
So `AWS_HANDLER=index.handler` means look for the export `handler` from `index.js`.
To use main.js, you'd change it to `AWS_HANDLER=main.handler`
