### ISSUE TITLE
Update to nodejs 14.x

### ISSUE THREAD

**Issue by jeanguerin** [motdotla/node-lambda#552]
Hello,

AWS released nodejs 14.x as runtime for Lambda early february. Unfortunately when I updated my launch configuration for node-lambda to "AWS_RUNTIME=nodejs14.x", VS code debug console exits with code 254. 

Could you help me please?

Jean

**Comment by abetomo** [comment]
Thanks for the report.
I've opened a PR that supports nodejs14.x. #553
