### ISSUE TITLE
Zip is not recognized as internal or external command

### ISSUE THREAD

**Issue by zeeshanjan82** [motdotla/node-lambda#57]
I am trying to use node-lambda on windows and I am getting this error when trying to deploy using node-lambda deploy. I am sure this will work on linux or mac but how can I deploy on windows. Do I need to install anything.

**Comment by DeviaVir** [comment]
You'll need to get a `zip` handler in your path, perhaps the following resource can help:
http://www.pcreview.co.uk/threads/zip-from-command-line.2699663/

**Comment by DeviaVir** [comment]
Also now there is bash on windows there's a plethora of solutions for this problem, all unrelated to this project.

http://www.zdnet.com/article/ubuntu-and-bash-arrive-on-windows-10/
