### ISSUE TITLE
rsync fails for private modules

### ISSUE THREAD

**Issue by justinmchase** [motdotla/node-lambda#59]
This line:
https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L162

Assumes that the name of the project is a single identifier but if you're using private npm modules you may end up with a package name such as:
```
"name": "@example/project-name"
```

The `/` in the name ends up generating a bad path here and rsync fails with an error like:
```
rsync: mkdir "/var/folders/vf/mr4h337s5jb8_w86q8p7372c0000gn/T/@example/project-name-1456433057973" failed: No such file or directory (2)
```

**Comment by DeviaVir** [comment]
Duplicates #37
