### ISSUE TITLE
How to test node.js api locally 

### ISSUE THREAD

**Issue by nirmalgoswami** [motdotla/node-lambda#60]
i am writing to get information from owner,,i am using express js and making web api using express js...i would like to test api locally same as AWS API Gateway,i need to test conect.done etc locally...amazon lambda have different syntax then normal express api 
eg   res.json({"Message" : "Welcome to the project"}); but in amazon lambda this type of syntax is not working we need to use content.done like syntax

**Comment by DeviaVir** [comment]
Seems others ran into your problem: https://medium.com/@john.titus/how-to-run-a-node-js-express-app-in-amazon-s-aws-api-gateway-84a54d21dca7#.3f0ki63hq

**Comment by nirmalgoswami** [comment]
moved to other alternative because this is not active repo

**Comment by DeviaVir** [comment]
@nirmalgoswami Which repo do you think is the active one?

**Comment by nirmalgoswami** [comment]
@DeviaVir [Serverless](https://github.com/serverless/serverless)

i am pleased to welcome you :)
