### ISSUE TITLE
Add support for nodejs18x runtime

### ISSUE THREAD

**Issue by k0psutin** [motdotla/node-lambda#617]
AWS Lambda supports Nodejs 18.x runtime

https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/

I made a PR regarding Nodejs 18.x
https://github.com/motdotla/node-lambda/pull/616

**Comment by tbrains** [comment]
+1

**Comment by DeviaVir** [comment]
https://github.com/motdotla/node-lambda/pull/616
