### ISSUE TITLE
Support new Node v4.3 API when running locally

### ISSUE THREAD

**Issue by briandonahue** [motdotla/node-lambda#70]
Lambda now supports Node.js v4.3 and it has changed the API, most notably `done()`, `succeed()`, `fail()` are deprecated on the `context` object in favor of a `callback` object:

```
function handler (event, context, callback) {
...
}
```

`node-lambda` should support either API based on the `AWS_RUNTIME` value.

**Comment by briandonahue** [comment]
I am going to take a shot at creating a PR for this, but am adding an issue for visibility and/or in case anyone else is already working on it.

**Comment by DeviaVir** [comment]
:+1: @nahivtot tested the `AWS_RUNTIME` did what it was supposed to.

**Comment by briandonahue** [comment]
Wow. http://replygif.net/i/1449.gif

On Mon, Apr 11, 2016 at 5:12 AM Chase <notifications@github.com> wrote:

> [image: :+1:] @nahivtot tested the AWS_RUNTIME did what it was supposed
> to.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/motdotla/node-lambda/issues/70#issuecomment-208243809>
>
-- 
Brian Donahue
Vitreo, LLC
215.586.3965

**Comment by DeviaVir** [comment]
@briandonahue we might still need to adjust:

> most notably done(), succeed(), fail() are deprecated on the context object in favor of a callback object

though?!

**Comment by briandonahue** [comment]
Well, I shouldn't write PRs on Fridays or respond on Mondays :)  Can't even gif right!  Yeah, I was kind of assuming something would need to change and I skimmed the code looking for the callback signature stuff and didn't see it.

![nevermind](http://replygif.net/i/1449.gif)

**Comment by briandonahue** [comment]
OK, I got back to this and confirmed my suspicion - `node-lambda run` doesn't work as expected because there is no `callback` being passed.  I created one and added support for passing along the runtime version and showing a deprecation message if using the context object for completion with `nodejs4.3` runtime.
