### ISSUE TITLE
AWS_ROLE issue

### ISSUE THREAD

**Issue by dstauffer** [motdotla/node-lambda#77]
when I run node-module setup, in the generated .env file it has the Key 'AWS_ROLE_ARN'.

When trying to deploy I get an error `[ValidationException: 1 validation error detected: Value 'missing' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+]`

The Role was coming through as missing

```
{
...
Role: 'missing',
...
}
```

In order to fix this, I just had to switch the `AWS_ROLE_ARN` to be `AWS_ROLE`

**Comment by DeviaVir** [comment]
@dstauffer it looks like both are supported: https://github.com/motdotla/node-lambda/blob/master/bin/node-lambda#L18, will need to do some more testing to see what exactly caused this for you

**Comment by DeviaVir** [comment]
I could not reproduce this problem, let me know if this is still an issue for you.
