### ISSUE TITLE
run debugging?

### ISSUE THREAD

**Issue by labithiotis** [motdotla/node-lambda#79]
Is there any way to setup debugging when you use run, I use webstorm and would be very useful.

**Comment by DeviaVir** [comment]
Hi @labithiotis `run`  is meant to be used for debugging, so I don't really follow your question. I don't make use of webstorm, so perhaps that is also why I'm not understanding your question, if you wish to extend node-lambda to support whatever you need, feel free to send in a PR for consideration.

Thanks!

**Comment by BigDSK** [comment]
@labithiotis In Webstorm, just configure a node.js run/debug configuration:
- 'JavaScript file' -> 'node_modules/node-lambda/bin/node-lambda'
- 'Application parameters' -> run --handler YOUR_HANDLER
- Set your env vars as required.

You can now debug in WS.

**Comment by civicevolution** [comment]
@BigDSK, thanks for the tip. 

Config is very easy. I've added a few notes and a screenshot to save others a bit of guessing:

 Webstorm Run/Debug Configuration
      Node.js
        Name                Email Lambda
        Node interpreter    ~/.nvm/versions/v4.3.2/bin/node
        Working directory   /ce_development/koa/t1/lambda/email-lambda
        Javascript file     node_modules/node-lambda/bin/node-lambda
        Application params  run

![run_debug_configurations](https://cloud.githubusercontent.com/assets/223139/17152346/3432bc66-532c-11e6-84c8-1de0addb8c9f.jpg)

**Comment by mrchief** [comment]
And in case you use VS COde, here's a launch configuration:

```
        {
            "type": "node",
            "request": "launch",
            "name": "Debug Program",
            "program": "${workspaceRoot}/node_modules/.bin/node-lambda",
            "args": ["run"]
        }
```
