### ISSUE TITLE
error during packaging

### ISSUE THREAD

**Issue by dng-dev** [motdotla/node-lambda#88]
I startet the package process like this 
`node-lambda package -e staging -f staging.env`

this results into the following error
`
/usr/lib64/node_modules/node-lambda/lib/main.js:270
  var handlerFileName = codeDirectory + '/' + program.handler.split('.').shift() + '.js';
                                                             ^

TypeError: Cannot read property 'split' of undefined
    at Lambda._setEnvironmentVars (/usr/lib64/node_modules/node-lambda/lib/main.js:270:62)
    at /usr/lib64/node_modules/node-lambda/lib/main.js:357:19
    at /usr/lib64/node_modules/node-lambda/lib/main.js:195:7
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
`

**Comment by DeviaVir** [comment]
@dng-dev did you set `AWS_HANDLER` to an empty value, or not at all in your `.env`?

**Comment by mitja123** [comment]
Yes its set in the file  `AWS_HANDLER=index.handler`

**Comment by mitja123** [comment]
It is easy to reproduce, copy the .env file to stage.env file and add it via -f to the package command.

**Comment by DeviaVir** [comment]
@dng-dev @mitja123 please review #90 to see if it solves the problems you're having

**Comment by dng-dev** [comment]
worked like a charm. added rsync patch and also the one you mentioned

**Comment by DeviaVir** [comment]
@dng-dev for the version bump, please watch https://github.com/motdotla/node-lambda/pull/92

**Comment by DeviaVir** [comment]
@dng-dev be advised, `0.8.1` including these fixes is now available

**Comment by dng-dev** [comment]
Great will check it out

Am Dienstag, 26. April 2016 schrieb Chase :
