### ISSUE TITLE
Lambda is not running all the time hence global initialisation happens every time.

### ISSUE THREAD

**Issue by vmasule** [motdotla/node-lambda#93]
I have a lambda where I assign some values to global variables, first time it works fine but second time it again initialises the global variable to default value. How can I run the local lambda like remote serverless lambda.
Also, If one lambda calls to other lambda how both lambdas will be up and running?

Please let me know if there anything I can do to achieve this.

**Comment by DeviaVir** [comment]
You should not see lambda as something that is always running, as an event-driven infrastructure it's only running when it has events to handle. The `run` command we expose can be used to test a certain environment with certain variables, if you wish to connect two lambda functions I would advise you to grab the output from the first lambda, and pass it through to the other, that way you can test if it works.

I hope that answers the question!

**Comment by vmasule** [comment]
Ok, Thank you very much. Appreciated.
