### ISSUE TITLE
how to set nodejs 4.3 in .env file?

### ISSUE THREAD

**Issue by sabrinaluo** [motdotla/node-lambda#94]
AWS recently supported nodejs 4.3, how can we set it in `.env` file? thank you.

**Comment by DeviaVir** [comment]
@sabrinaluo please refer to the docs on the homepage:
https://github.com/motdotla/node-lambda#run
https://github.com/motdotla/node-lambda#deploy
These allow you to specify `-u` / `--runtime`

To pass it on via your `.env` file, please see the sample `.env` file here:
https://github.com/motdotla/node-lambda/blob/master/lib/.env.example#L12

**Comment by sabrinaluo** [comment]
thank you, this is helpful. :)
