### ISSUE TITLE
Inconsistency between ZIP generated with node-lambda package and node-lambda deploy

### ISSUE THREAD

**Issue by green-mdoerflinger** [motdotla/node-lambda#96]
Hi,

When i generate a ZIP using ```node-lambda package```, then this ZIP contains everything that is currently in my project directory, including .env, deploy.env, event.json ... It also contains files excluded in ```.env``` _EXCLUDE_GLOBS_. 
When i deploy to AWS using `node-lambda deploy` and then download the ZIP file that was uploaded to AWS this file is not the same that was generated with node-lambda package (it no longer contains unnecessary files mentioned above). I would expect the ZIP file created with `node-lambda package` to be the same as the one uploaded with the deploy command. 
Do i misunderstand the package command or is this a bug? 

Thanks, Marc

**Comment by DeviaVir** [comment]
Hi Marc,

The package and deploy command both pass the packaging on to the same function: https://github.com/motdotla/node-lambda/blob/master/lib/main.js#L328
it is possible you were testing while we were fixing excludes, do you still have this problem? If so, it's definitely a bug.

**Comment by DeviaVir** [comment]
Did some more testing, and ended up in #104, which has been deployed to `0.8.3` on NPM. Thanks for pointing this out!
