### ISSUE TITLE
Using AWS IAM role/user in the lambda

### ISSUE THREAD

**Issue by romain-nio** [motdotla/node-lambda#98]
Hi,

Thanks so much for your tool, I love it :)

Just one question about lambda functions requesting other AWS services where authentification is needed (for example cloudsearch with 'aws-sdk" node.js module). Is-it possible to directly specify to node-lambda the IAM role to use in the "run" mode ? I tried to add it to context.json whitout any success :)

If I add the line below in my script it works, but I'm looking for a way to not add it to the JS code :)
`AWS.config.update({region:'eu-west-1',accessKeyId: 'XXXX', secretAccessKey: 'XXXX'});
`
Thanks!
Romain.

**Comment by romain-nio** [comment]
just found the `.env` file ! :) :+1:

**Comment by DeviaVir** [comment]
Yeah, that's the way! Let us know if we can help with anything else, good luck!
